### ISSUE TITLE
Adding long and date columns throws SQLException

### ISSUE THREAD

**Issue by simoc** [simoc/csvjdbc#56]
For the following CSV file `events.csv`:

    start_date,duration,name
    2023-01-01,365,"centenary year"
    2023-03-01,31,"book month"

CsvJdbc throws an SQL Exception when executing an SQL query adding a column with type `long` and a column with type `date`. The following sample code demonstrates this:

    Properties props = new Properties();
    props.put("columnTypes", "date,long,string");
    Connection conn1 = DriverManager.getConnection("jdbc:relique:csv:c:/temp", props);
    ResultSet results1 = conn1.createStatement().executeQuery("SELECT name, start_date, duration + start_date FROM events");
    while (results1.next())
    {
      System.out.println(results1.getString(1));
      System.out.println(results1.getDate(2));
      System.out.println(results1.getDate(3));
    }

    centenary year
    2023-01-01
    Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.sql.Date (java.lang.String is in module java.base of loader 'bootstrap'; java.sql.Date is in module java.sql of loader 'platform')
	at org.relique.jdbc.csv.CsvResultSet.getDate(CsvResultSet.java:1254)
	at org.relique.jdbc.csv.DemoDriver10.main(DemoDriver10.java:19)

CsvJdbc runs correctly if the column has type `int` instead of `long`, or the expression in the SQL statement is `start_date + duration`.

**Comment by simoc** [comment]
To fix this problem, change the variable from `rightEval` to `leftEval` here:

 https://github.com/simoc/csvjdbc/blob/1dbb43f998074516bb684767c94cc2914f6a6139/src/main/java/org/relique/jdbc/csv/BinaryOperation.java#L184
